# Generated by Django 5.2.1 on 2025-05-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_lawyerreview"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PracticeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="lawyerprofile",
            name="language",
        ),
        migrations.RemoveField(
            model_name="lawyerprofile",
            name="practice_area",
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="languages",
            field=models.ManyToManyField(to="app.language"),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="practice_areas",
            field=models.ManyToManyField(to="app.practicearea"),
        ),
    ]
