# Generated by Django 5.2.1 on 2025-05-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_language_practicearea_remove_lawyerprofile_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lawyerprofile",
            name="languages",
        ),
        migrations.RemoveField(
            model_name="lawyerprofile",
            name="practice_areas",
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="language",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lawyerprofile",
            name="practice_area",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name="Language",
        ),
        migrations.DeleteModel(
            name="PracticeArea",
        ),
    ]
