# Generated by Django 5.2.1 on 2025-05-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_remove_lawyerprofile_languages_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lawyerprofile",
            name="language",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lawyerprofile",
            name="practice_area",
            field=models.TextField(blank=True, null=True),
        ),
    ]
