# Generated by Django 5.2.1 on 2025-06-06 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_case"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="lawyer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases_as_lawyer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
