# Generated by Django 5.2.1 on 2025-06-14 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_appointment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="availableslot",
            name="lawyer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
