# Generated by Django 5.2.1 on 2025-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_availableslot_lawyer"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="deleted_by_receiver",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_by_sender",
            field=models.BooleanField(default=False),
        ),
    ]
