# Generated by Django 5.2.1 on 2025-06-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_alter_case_options_case_updated_at_alter_case_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="case",
            options={},
        ),
        migrations.RemoveField(
            model_name="case",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.CharField(
                choices=[
                    ("Reviewing", "Reviewing"),
                    ("Filed", "Filed"),
                    ("In Court", "In Court"),
                    ("Closed", "Closed"),
                ],
                max_length=50,
            ),
        ),
        migrations.DeleteModel(
            name="CaseDocument",
        ),
    ]
