# Generated by Django 5.2.1 on 2025-06-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_casedocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="client_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
