# Generated by Django 5.2.1 on 2025-06-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0022_case_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="file_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="file_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
