# Generated by Django 5.2.1 on 2025-06-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_message_file_size_message_file_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="message",
            name="file_type",
        ),
    ]
