# Generated by Django 5.2.1 on 2025-06-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0024_remove_message_file_size_remove_message_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="email",
            field=models.EmailField(default="noreply@example.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="name",
            field=models.CharField(default="Anonymous User", max_length=100),
            preserve_default=False,
        ),
    ]
