# Generated by Django 5.2.1 on 2025-06-19 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_alter_answer_options_alter_question_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="anonymous_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="anonymous_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("lawyer", "Lawyer"),
                    ("visitor", "Visitor"),
                ],
                default="visitor",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
