# Generated by Django 5.2.1 on 2025-06-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_feedback_anonymous_email_feedback_anonymous_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="user_type",
            field=models.CharField(
                choices=[("lawyer", "Lawyer"), ("visitor", "Visitor")],
                default="visitor",
                max_length=20,
            ),
        ),
    ]
