# Generated by Django 5.2.1 on 2025-06-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_alter_feedback_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
